[package]
name = "quack_ml"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = {version = "1.0.0", features = ["vtab-loadable"]}
duckdb-loadable-macros = "0.1.2"
flate2 = "1.0.32"
lazy_static = "1.5.0"
libduckdb-sys = {version = "1.0.0", features = ["bundled", "buildtime_bindgen"]}
serde = "1.0.208"

[lib]
crate-type = ["cdylib"]
name = "quack_ml"
